package gui;
import session.SessionManager;
import database.DatabaseUtils;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.SwingUtilities;

/**
 *
 * @author Luisa Eustaquio
 */
public class AdminReviewDialog extends javax.swing.JDialog {

    /**
     * Creates new form AdminReviewDialog
     */
    public AdminReviewDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        getLoggedInUserID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEdit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDelivery = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblService = new javax.swing.JLabel();
        lblAddOns = new javax.swing.JLabel();
        lblDropOff = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCompleted = new javax.swing.JLabel();
        lblPaid = new javax.swing.JLabel();
        lblKilo = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Transaction Details");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 730, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("Service:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        lblNote.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblNote.setText("jLabel1");
        getContentPane().add(lblNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 200, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setText("Add Ons:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, 20));

        lblDelivery.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblDelivery.setText("jLabel1");
        getContentPane().add(lblDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 170, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setText("Drop Off Date:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, 20));

        lblService.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblService.setText("jLabel1");
        getContentPane().add(lblService, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 150, -1));

        lblAddOns.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblAddOns.setText("jLabel1");
        getContentPane().add(lblAddOns, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 150, 20));

        lblDropOff.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblDropOff.setText("jLabel1");
        getContentPane().add(lblDropOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 150, 20));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("Customer Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Contact Number:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Customer Address:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        lblName.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblName.setText("jLabel1");
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 190, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Additional Note:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lblContact.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblContact.setText("jLabel1");
        getContentPane().add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 200, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("Delivery Method:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        lblAddress.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblAddress.setText("jLabel1");
        getContentPane().add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 200, -1));

        lblCompleted.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblCompleted.setText("jLabel1");
        getContentPane().add(lblCompleted, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 150, 20));

        lblPaid.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPaid.setText("jLabel1");
        getContentPane().add(lblPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 150, 20));

        lblKilo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblKilo.setText("jLabel1");
        getContentPane().add(lblKilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 150, 20));

        lblTotal.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblTotal.setText("jLabel1");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 150, 20));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setText("Completed Date:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setText("Payment Status:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 100, 20));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setText("Kilo:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, 20));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel12.setText("Total:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -220, 750, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int userID, transacID, finKilo, finTotal;
    private String finCompletedDate, finPaymentStatus;
    
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try (Connection conn = DatabaseUtils.getConnection();
            PreparedStatement stmt = conn.prepareStatement("UPDATE tbl_transactions SET t_kilo = ?, t_total = ?, t_completedDate = ?, t_paymentStatus = ? "
                    + "WHERE t_id = ?")) {

            stmt.setInt(1, finKilo);
            stmt.setInt(2, finTotal);
            stmt.setString(3, finCompletedDate);
            stmt.setString(4, finPaymentStatus);
            stmt.setInt(5, transacID);

            int rowsUpdated = stmt.executeUpdate();
            if (rowsUpdated > 0) {
                System.out.println("Transaction details updated successfully!");
                javax.swing.JOptionPane.showMessageDialog(this, "Update successful!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                Window parentWindow = SwingUtilities.windowForComponent(this);
                parentWindow.dispose();
                dispose();
                AdminPanel adminPanel = new AdminPanel();
                adminPanel.setVisible(true);
            }
       } catch (SQLException ex) {
            ex.printStackTrace();
       }
    }//GEN-LAST:event_btnUpdateActionPerformed

    public void setReviewDetails(int transactionID, String name, String contact, String address, String submittedDate, String note, String service, String addOn, String deliveryMethod, String dropOffDate, String paymentStatus, String completedDate, int kilo, int total) {
        lblName.setText(name);
        lblContact.setText(contact);
        lblAddress.setText(address);
        lblNote.setText(note);
        lblService.setText(service);
        lblAddOns.setText(addOn);
        lblDelivery.setText(deliveryMethod);
        lblDropOff.setText(dropOffDate);
        lblPaid.setText(paymentStatus);
        lblCompleted.setText(completedDate);
        lblKilo.setText(Integer.toString(kilo));
        lblTotal.setText(Integer.toString(total));
        
        transacID = transactionID;
        finKilo = kilo;
        finTotal = total;
        finCompletedDate = completedDate;
        finPaymentStatus = paymentStatus;
    }
    
    private void getLoggedInUserID(){
        String username = SessionManager.getLoggedInUser();
    
        try (Connection conn = DatabaseUtils.getConnection();
             PreparedStatement stmt = conn.prepareStatement("SELECT u_id FROM tbl_users WHERE u_username = ?")) {
            stmt.setString(1, username);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    userID = rs.getInt("u_id");
                    System.out.println("User ID: " + userID);
                } else {
                    System.out.append("You are not logged in.");
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminReviewDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminReviewDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminReviewDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminReviewDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminReviewDialog dialog = new AdminReviewDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAddOns;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCompleted;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDelivery;
    private javax.swing.JLabel lblDropOff;
    private javax.swing.JLabel lblKilo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblPaid;
    private javax.swing.JLabel lblService;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
