package gui;

import java.text.SimpleDateFormat;

/**
 *
 * @author Luisa Eustaquio
 */
public class BookingFormPanel extends javax.swing.JFrame {

    /**
     * Creates new form BookingForm
     */
    public BookingFormPanel() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fldName = new javax.swing.JTextField();
        fldContact = new javax.swing.JTextField();
        fldAddress = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fldNote = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        cbDelivery = new javax.swing.JComboBox<>();
        cbService = new javax.swing.JComboBox<>();
        cbAddOns = new javax.swing.JComboBox<>();
        btnReview = new javax.swing.JButton();
        fldDate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fldName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldNameActionPerformed(evt);
            }
        });
        getContentPane().add(fldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 250, -1));

        fldContact.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(fldContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 250, -1));

        fldAddress.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(fldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 250, -1));

        fldNote.setColumns(20);
        fldNote.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fldNote.setRows(5);
        jScrollPane1.setViewportView(fldNote);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 420, -1));

        btnBack.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, -1));

        cbDelivery.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbDelivery.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pick up", "Deliver" }));
        cbDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDeliveryActionPerformed(evt);
            }
        });
        getContentPane().add(cbDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 162, -1));

        cbService.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fresh Essentials", "Gentle Care", "Sparkle & Shine", "Luxury Bliss", "Royal Elegance" }));
        cbService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbServiceActionPerformed(evt);
            }
        });
        getContentPane().add(cbService, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 162, -1));

        cbAddOns.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbAddOns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Pack 1", "Pack 2", "Pack 3", "Pack 4" }));
        cbAddOns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAddOnsActionPerformed(evt);
            }
        });
        getContentPane().add(cbAddOns, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 160, -1));

        btnReview.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnReview.setText("Review");
        btnReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewActionPerformed(evt);
            }
        });
        getContentPane().add(btnReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, -1, -1));
        getContentPane().add(fldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 162, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Booking Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 470, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Service Type:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Customer Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Contact Number:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Address:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Additional Note:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Drop off Date:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Delivery Method:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Add ons:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 470, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String selectedAddOn, selectedDelivery, selectedService, address, contact, name, note, tempDate;
    
    private void btnReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewActionPerformed
       reviewInput();
    }//GEN-LAST:event_btnReviewActionPerformed
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        int option = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to go back?", "Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);
        if (option == javax.swing.JOptionPane.YES_OPTION) {
            CustomerPanel customerPanel = new CustomerPanel();
            customerPanel.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void cbDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDeliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDeliveryActionPerformed

    private void cbServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbServiceActionPerformed

    private void cbAddOnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAddOnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAddOnsActionPerformed

    private void fldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldNameActionPerformed

    private void reviewInput() {
        selectedAddOn = (String) cbAddOns.getSelectedItem();
        selectedDelivery = (String) cbDelivery.getSelectedItem();
        selectedService = (String) cbService.getSelectedItem();
        address = fldAddress.getText();
        contact = fldContact.getText();
        name = fldName.getText();
        note = fldNote.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        tempDate = dateFormat.format(fldDate.getDate());
        CustomerReviewDialog customerReviewDialog = new CustomerReviewDialog(this, true);
        customerReviewDialog.setReviewDetails(address, contact, name, selectedService, selectedAddOn, selectedDelivery, note, tempDate);
        customerReviewDialog.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingFormPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingFormPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingFormPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingFormPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingFormPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReview;
    private javax.swing.JComboBox<String> cbAddOns;
    private javax.swing.JComboBox<String> cbDelivery;
    private javax.swing.JComboBox<String> cbService;
    private javax.swing.JTextField fldAddress;
    private javax.swing.JTextField fldContact;
    private com.toedter.calendar.JDateChooser fldDate;
    private javax.swing.JTextField fldName;
    private javax.swing.JTextArea fldNote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
