package gui;
import database.DatabaseUtils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;



/**
 *
 * @author Luisa Eustaquio
 */
public class UpdateTransacDetailsPanel extends javax.swing.JFrame {

    /**
     * Creates new form UpdateTransacDetailsPanel
     */
    public UpdateTransacDetailsPanel(int transactionID) {
        initComponents();
        this.setLocationRelativeTo(null);
        displayTransactionDetails(transactionID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblTransactionID = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        lblSubmittedDate = new javax.swing.JLabel();
        lblPaymentStatus = new javax.swing.JLabel();
        lblTransacStatus = new javax.swing.JLabel();
        lblDropOff = new javax.swing.JLabel();
        lblService = new javax.swing.JLabel();
        lblAddOn = new javax.swing.JLabel();
        lblDelivery = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fldKilo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fldTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dcCompleted = new com.toedter.calendar.JDateChooser();
        cbPayment = new javax.swing.JCheckBox();
        btnReview = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(212, 225, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(202, 210, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblName.setText("jLabel1");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 93, -1, -1));

        lblContact.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblContact.setText("jLabel2");
        jPanel1.add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 138, -1, -1));

        lblAddress.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblAddress.setText("jLabel3");
        jPanel1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 183, -1, -1));

        lblTransactionID.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblTransactionID.setText("jLabel1");
        jPanel1.add(lblTransactionID, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 48, -1, -1));

        lblNote.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblNote.setText("jLabel3");
        jPanel1.add(lblNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        lblSubmittedDate.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblSubmittedDate.setText("jLabel3");
        jPanel1.add(lblSubmittedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        lblPaymentStatus.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPaymentStatus.setText("jLabel3");
        jPanel1.add(lblPaymentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        lblTransacStatus.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblTransacStatus.setText("jLabel3");
        jPanel1.add(lblTransacStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 50, 20));

        lblDropOff.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblDropOff.setText("jLabel3");
        jPanel1.add(lblDropOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        lblService.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblService.setText("jLabel3");
        jPanel1.add(lblService, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        lblAddOn.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblAddOn.setText("jLabel3");
        jPanel1.add(lblAddOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        lblDelivery.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblDelivery.setText("delivrymeth");
        jPanel1.add(lblDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setText("Transaction ID:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setText("Customer Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setText("Contact Number:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setText("Address:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setText("Payment Status:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel12.setText("Service Type:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel13.setText("Drop off Date:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel14.setText("Add ons:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel15.setText("Date Submitted:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel16.setText("Transaction Status:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel17.setText("Additional Note:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel18.setText("Delivery Method:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("Kilo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        fldKilo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.add(fldKilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 110, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Total Cost:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        fldTotal.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jPanel1.add(fldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 110, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("Date Completed:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));
        jPanel1.add(dcCompleted, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 110, -1));

        cbPayment.setBackground(new java.awt.Color(211, 223, 251));
        cbPayment.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cbPayment.setText("Paid");
        jPanel1.add(cbPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 630, 310));

        btnReview.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnReview.setText("Review");
        btnReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewActionPerformed(evt);
            }
        });
        getContentPane().add(btnReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int transacID;
    private String name, contact, address, submittedDate, service, addOn, note, transacStatus, paymentStatus, deliveryMethod, dropOffDate, completedDate;
    private int kilo, total;
    
    private void btnReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewActionPerformed
        String kiloText = fldKilo.getText();
        String totalText = fldTotal.getText();
        
        if (kiloText.isEmpty() || totalText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill up the kilo and total fields first.", "Missing Information", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        kilo = Integer.parseInt(kiloText);
        total = Integer.parseInt(totalText);
        
        if (dcCompleted.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            completedDate = sdf.format(dcCompleted.getDate());
        }
        
        String paymentStatus = cbPayment.isSelected() ? "paid" : "pending";
        
        AdminReviewDialog adminReviewDialog = new AdminReviewDialog(this, true);
        adminReviewDialog.setReviewDetails(transacID, name, contact, address, submittedDate, note, service, addOn, deliveryMethod, dropOffDate, paymentStatus, completedDate, kilo, total);
        adminReviewDialog.setVisible(true);
    }//GEN-LAST:event_btnReviewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminPanel adminPanel = new AdminPanel();
        adminPanel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void displayTransactionDetails(int transactionID) {
        transacID = transactionID;
        try (Connection conn = DatabaseUtils.getConnection();
            PreparedStatement stmt = conn.prepareStatement("SELECT c.c_name, c.c_contact, c.c_address, t.s_id, t.a_id, s.s_name, a.a_name, t.t_kilo, t.t_total, t.t_dropOffDate, t.t_deliveryMethod, t.t_submittedDate, t.t_completedDate, t.t_kilo, t.t_total, t.t_note, t.t_transacStatus, t.t_paymentStatus "
                    + "FROM tbl_transactions t "
                    + "INNER JOIN tbl_customers c ON t.c_id = c.c_id "
                    + "INNER JOIN tbl_services s ON t.s_id = s.s_id "
                    + "INNER JOIN tbl_addons a ON t.a_id = a.a_id "
                    + "WHERE t.t_id = ?")) {
            stmt.setInt(1, transactionID);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    name = rs.getString("c_name");
                    contact = rs.getString("c_contact");
                    address = rs.getString("c_address");
                    submittedDate = rs.getString("t_submittedDate");
                    note = rs.getString("t_note");
                    transacStatus = rs.getString("t_transacStatus");
                    paymentStatus = rs.getString("t_paymentStatus");
                    deliveryMethod = rs.getString("t_deliveryMethod");
                    dropOffDate = rs.getString("t_dropOffDate");
                    completedDate = rs.getString("t_completedDate");
                    service = rs.getString("s_name");
                    addOn = rs.getString("a_name");
                    kilo = rs.getInt("t_kilo");
                    total = rs.getInt("t_total");
                    
                    lblTransactionID.setText(String.valueOf(transactionID));
                    lblName.setText(name);
                    lblContact.setText(contact);
                    lblAddress.setText(address);
                    lblSubmittedDate.setText(submittedDate);
                    lblNote.setText(note);
                    lblTransacStatus.setText(transacStatus);
                    lblPaymentStatus.setText(paymentStatus);
                    lblDropOff.setText(dropOffDate);
                    lblService.setText(service);
                    lblAddOn.setText(addOn);
                    fldKilo.setText(String.valueOf(kilo));
                    fldTotal.setText(String.valueOf(total));
                    lblDelivery.setText(deliveryMethod);
                     
                    if (completedDate != null && !completedDate.isEmpty()) {
                        try {
                            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                            Date date = dateFormat.parse(completedDate);
                            dcCompleted.setDate(date);
                        } catch (ParseException ex) {
                            ex.printStackTrace();
                        }
                    }
                    
                    cbPayment.setSelected(paymentStatus.equalsIgnoreCase("paid"));
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTransacDetailsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTransacDetailsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTransacDetailsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTransacDetailsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int transactionID = 0;
                new UpdateTransacDetailsPanel(transactionID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReview;
    private javax.swing.JCheckBox cbPayment;
    private com.toedter.calendar.JDateChooser dcCompleted;
    private javax.swing.JTextField fldKilo;
    private javax.swing.JTextField fldTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddOn;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDelivery;
    private javax.swing.JLabel lblDropOff;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblPaymentStatus;
    private javax.swing.JLabel lblService;
    private javax.swing.JLabel lblSubmittedDate;
    private javax.swing.JLabel lblTransacStatus;
    private javax.swing.JLabel lblTransactionID;
    // End of variables declaration//GEN-END:variables
}
