package gui;
import database.DatabaseUtils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;



/**
 *
 * @author Luisa Eustaquio
 */
public class UpdateTransacDetailsPanel extends javax.swing.JFrame {

    /**
     * Creates new form UpdateTransacDetailsPanel
     */
    public UpdateTransacDetailsPanel(int transactionID) {
        initComponents();
        this.setLocationRelativeTo(null);
        displayTransactionDetails(transactionID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblTransactionID = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        lblSubmittedDate = new javax.swing.JLabel();
        lblPaymentStatus = new javax.swing.JLabel();
        lblTransacStatus = new javax.swing.JLabel();
        lblDropOff = new javax.swing.JLabel();
        lblService = new javax.swing.JLabel();
        lblAddOn = new javax.swing.JLabel();
        lblDelivery = new javax.swing.JLabel();
        cbPayment = new javax.swing.JCheckBox();
        dcCompleted = new com.toedter.calendar.JDateChooser();
        btnReview = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        fldKilo = new javax.swing.JTextField();
        fldTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblName.setText("jLabel1");

        lblContact.setText("jLabel2");

        lblAddress.setText("jLabel3");

        lblTransactionID.setText("jLabel1");

        lblNote.setText("jLabel3");

        lblSubmittedDate.setText("jLabel3");

        lblPaymentStatus.setText("jLabel3");

        lblTransacStatus.setText("jLabel3");

        lblDropOff.setText("jLabel3");

        lblService.setText("jLabel3");

        lblAddOn.setText("jLabel3");

        lblDelivery.setText("delivrymeth");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTransactionID)
                            .addComponent(lblAddress)
                            .addComponent(lblContact)
                            .addComponent(lblName))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(lblDropOff))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNote)
                                            .addComponent(lblSubmittedDate)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(lblService)))
                                .addGap(114, 114, 114)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPaymentStatus)
                                    .addComponent(lblTransacStatus)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDelivery)
                                .addGap(141, 141, 141))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(lblAddOn)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddOn)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblTransacStatus)
                            .addGap(33, 33, 33)
                            .addComponent(lblPaymentStatus))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblTransactionID)
                            .addGap(18, 18, 18)
                            .addComponent(lblName)
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(lblDelivery)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblAddress)
                                        .addComponent(lblDropOff)))
                                .addComponent(lblContact))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblService)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSubmittedDate)
                        .addGap(49, 49, 49)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        cbPayment.setText("Paid");

        btnReview.setText("Review");
        btnReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Kilo");

        jLabel2.setText("Total cost");

        jLabel3.setText("compl");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3)
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dcCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(btnBack)
                                .addGap(18, 18, 18)
                                .addComponent(btnReview))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(fldKilo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cbPayment)
                                    .addComponent(fldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fldKilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbPayment)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dcCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBack)
                        .addComponent(btnReview)))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int transacID;
    private String name, contact, address, submittedDate, service, addOn, note, transacStatus, paymentStatus, deliveryMethod, dropOffDate, completedDate;
    private int kilo, total;
    
    private void btnReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewActionPerformed
        String kiloText = fldKilo.getText();
        String totalText = fldTotal.getText();
        
        if (kiloText.isEmpty() || totalText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill up the kilo and total fields first.", "Missing Information", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        kilo = Integer.parseInt(kiloText);
        total = Integer.parseInt(totalText);
        
        if (dcCompleted.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            completedDate = sdf.format(dcCompleted.getDate());
        }
        
        String paymentStatus = cbPayment.isSelected() ? "paid" : "pending";
        
        AdminReviewDialog adminReviewDialog = new AdminReviewDialog(this, true);
        adminReviewDialog.setReviewDetails(transacID, name, contact, address, submittedDate, note, service, addOn, deliveryMethod, dropOffDate, paymentStatus, completedDate, kilo, total);
        adminReviewDialog.setVisible(true);
    }//GEN-LAST:event_btnReviewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminPanel adminPanel = new AdminPanel();
        adminPanel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void displayTransactionDetails(int transactionID) {
        transacID = transactionID;
        try (Connection conn = DatabaseUtils.getConnection();
            PreparedStatement stmt = conn.prepareStatement("SELECT c.c_name, c.c_contact, c.c_address, t.s_id, t.a_id, s.s_name, a.a_name, t.t_kilo, t.t_total, t.t_dropOffDate, t.t_deliveryMethod, t.t_submittedDate, t.t_completedDate, t.t_kilo, t.t_total, t.t_note, t.t_transacStatus, t.t_paymentStatus "
                    + "FROM tbl_transactions t "
                    + "INNER JOIN tbl_customers c ON t.c_id = c.c_id "
                    + "INNER JOIN tbl_services s ON t.s_id = s.s_id "
                    + "INNER JOIN tbl_addons a ON t.a_id = a.a_id "
                    + "WHERE t.t_id = ?")) {
            stmt.setInt(1, transactionID);
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    name = rs.getString("c_name");
                    contact = rs.getString("c_contact");
                    address = rs.getString("c_address");
                    submittedDate = rs.getString("t_submittedDate");
                    note = rs.getString("t_note");
                    transacStatus = rs.getString("t_transacStatus");
                    paymentStatus = rs.getString("t_paymentStatus");
                    deliveryMethod = rs.getString("t_deliveryMethod");
                    dropOffDate = rs.getString("t_dropOffDate");
                    completedDate = rs.getString("t_completedDate");
                    service = rs.getString("s_name");
                    addOn = rs.getString("a_name");
                    kilo = rs.getInt("t_kilo");
                    total = rs.getInt("t_total");
                    
                    lblTransactionID.setText(String.valueOf(transactionID));
                    lblName.setText(name);
                    lblContact.setText(contact);
                    lblAddress.setText(address);
                    lblSubmittedDate.setText(submittedDate);
                    lblNote.setText(note);
                    lblTransacStatus.setText(transacStatus);
                    lblPaymentStatus.setText(paymentStatus);
                    lblDropOff.setText(dropOffDate);
                    lblService.setText(service);
                    lblAddOn.setText(addOn);
                    fldKilo.setText(String.valueOf(kilo));
                    fldTotal.setText(String.valueOf(total));
                    lblDelivery.setText(deliveryMethod);
                     
                    if (completedDate != null && !completedDate.isEmpty()) {
                        try {
                            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                            Date date = dateFormat.parse(completedDate);
                            dcCompleted.setDate(date);
                        } catch (ParseException ex) {
                            ex.printStackTrace();
                        }
                    }
                    
                    cbPayment.setSelected(paymentStatus.equalsIgnoreCase("paid"));
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTransacDetailsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTransacDetailsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTransacDetailsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTransacDetailsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int transactionID = 0;
                new UpdateTransacDetailsPanel(transactionID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReview;
    private javax.swing.JCheckBox cbPayment;
    private com.toedter.calendar.JDateChooser dcCompleted;
    private javax.swing.JTextField fldKilo;
    private javax.swing.JTextField fldTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddOn;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDelivery;
    private javax.swing.JLabel lblDropOff;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblPaymentStatus;
    private javax.swing.JLabel lblService;
    private javax.swing.JLabel lblSubmittedDate;
    private javax.swing.JLabel lblTransacStatus;
    private javax.swing.JLabel lblTransactionID;
    // End of variables declaration//GEN-END:variables
}
